oleg_test:
    path: /
    defaults: { _controller: OlegTestBundle:Test:test }

portfolio:
    path: /portfolio
    defaults: { _controller: OlegTestBundle:Portfolio:portfolio }

portfolio_view:
    path: /portfolio/view/{id}
    defaults: { _controller: OlegTestBundle:Portfolio:view }
    
portfolio_del:
    path: /portfolio/del/{id}
    defaults: { _controller: OlegTestBundle:Portfolio:del }
    
news_index:
    path: /news
    defaults: { _controller: OlegTestBundle:News:news }
    
news_view:
    path: /news/view/{slug}
    defaults: { _controller: OlegTestBundle:News:view }
    
news_del:
    path: /news/del/{slug}
    defaults: { _controller: OlegTestBundle:News:delArticle }

news_edit:
    path: /news/edit/{slug}
    defaults: { _controller: OlegTestBundle:News:editArticle }

news_add:
    path: /news/add
    defaults: { _controller: OlegTestBundle:News:addArticle }

news_search:
    path: /news/search
    defaults: { _controller: OlegTestBundle:News:searchArticles }
    
test_ajax:
    path: /ajax
    defaults: { _controller: OlegTestBundle:Ajax:testAjax }
    
ajax_action:
    path: /ajax2
    defaults: { _controller: OlegTestBundle:Ajax:ajax }