services:
#    oleg_test.example:
#        class: Oleg\TestBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    news_manager:
        class: Oleg\TestBundle\Service\NewsManager
        arguments: 
            - @service_container

    admin.news:
        class: Oleg\TestBundle\Admin\ArticleAdmin
        arguments: [~, Oleg\TestBundle\Entity\News, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Новости }
            
    admin.category:
        class: Oleg\TestBundle\Admin\CategoryAdmin
        arguments: [~, Oleg\TestBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Категории }
            
    admin.post:
        class: Oleg\TestBundle\Admin\PostAdmin
        arguments: [~, Oleg\TestBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Записи }