Oleg\TestBundle\Entity\Category:
    type: entity
    table: category
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        slug:
            type: string
            length: 255
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            column: updated_at
    oneToMany:
        news:
            targetEntity: News
            mappedBy: category
    lifecycleCallbacks: {  }
