Oleg\TestBundle\Entity\News:
    type: entity
    table: news
    repositoryClass: Oleg\TestBundle\Repository\NewsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '255'
        description:
            type: string
            length: '1000'
            nullable: true
        content:
            type: string
            length: '4000'
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: news
            joinColumn:
              name: category_id
              referencedColumnName: id
    lifecycleCallbacks: {  }
