<?php

namespace Oleg\TestBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNewsBySlug($slug)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->andWhere('n.slug = :slug')
                ->setParameter(':slug', $slug);

        return $qb->getQuery()->getResult();
    }
    
    public function getArticle()
    {

        
//        $em = $this->get('doctrine.orm.entity_manager');
//        $news = $em->createQuery('select n from OlegTestBundle:News n '
//                . ' inner join OlegTestBundle:Category c '
//                . 'where n.category_id = c.id')
//             ->getResult();
    }
}
