<?php

namespace Oleg\TestBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNewsByTitle($title)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->andWhere('n.title = :title')
                ->setParameter(':title', $title);

        return $qb->getQuery()->getResult();
    }
}
