<?php

namespace Oleg\TestBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNewsBySlug($slug)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->andWhere('n.slug = :slug')
                ->setParameter(':slug', $slug);

        return $qb->getQuery()->getResult();
    }
    
    public function getArticle()
    {
        $qb = $this->createQueryBuilder('n');
        $qb->orderBy('n.updatedAt', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
    
    public function search($str)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->andwhere('n.title LIKE :title')
               ->setParameter('title', '%'.$str.'%');
        
        return $qb->getQuery()->getResult();
    }
}
