<?php

namespace Oleg\TestBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function countPosts()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('COUNT(p.id)');
        return $qb->getQuery()->getSingleScalarResult();
    }
}
